name: Build WebApp
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with: { node-version: 22 }
      - name: Install
        run: npm install --no-audit --no-fund --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: SmartStruct_RJP_WebApp
          path: dist
